### ISSUE TITLE
quicksort!(x) doing an out of place sort

### ISSUE THREAD

**Issue by thepulkitagarwal** [Dawny33/SearchSortAlgos.jl#6]
If you do

``` julia
c = [23, 12, 17, 88, 90, 26, 34, 129]
println(c)
println(quicksort!(c))
println(c)
```

It gives

``` julia
[23,12,17,88,90,26,34,129]
Any[12,17,23,26,34,88,90,129]
[23,12,17,88,90,26,34,129]
```

So should it be renamed from quicksort!(x) to quicksort(x), or should the function be modified to do an in-place sort instead?

**Comment by Dawny33** [comment]
Renaming would disturb the naming convention (which leads to confusion for the user.)
So, I'd vote for in-place implementation. 

Do let me know if you want to send in a PR, implementing the same!

**Comment by Dawny33** [comment]
In-place `quicksort!` implemented

**Comment by thepulkitagarwal** [comment]
Sorry for not replying earlier, I did not see your message.

**Comment by Dawny33** [comment]
It's okay.  Thanks for raising the issue.  

In-place is always sexy  :wink:

**Comment by thepulkitagarwal** [comment]
:joy:
