### ISSUE TITLE
Similar Package Exists

### ISSUE THREAD

**Issue by thepulkitagarwal** [Dawny33/SearchSortAlgos.jl#8]
https://github.com/JuliaLang/SortingAlgorithms.jl

**Comment by Dawny33** [comment]
@thepulkitagarwal Yeah, I was aware of it.  Thanks for raising the issue :smile: 

My aim was to include more diverse search and sort algorithms like MonteCarlo Search, etc.  [Helpful link](https://github.com/svaksha/Julia.jl/issues/58#issuecomment-193319873)

**Comment by thepulkitagarwal** [comment]
:smiley:
